// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niaehwdbquyqpinibtba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pYWVod2RicXV5cXBpbmlidGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTQ0OTUsImV4cCI6MjA1NTg3MDQ5NX0.uIBgD4KZjx0OJFBlO9sMQ9geAZGoX5dnEBvaFbk_Ffg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);